### ISSUE TITLE
Cataclysm Multiplayer

### ISSUE THREAD

**Issue by SeaBook27** [Steviegt6/CataclysmMod#13]
I have found recently that the cataclysm mod works perfectly during singleplayer on tmodloader utilizing version 1.3.5.3 however, when attempting to host a multiplayer server, Cataclysm is force disabled before the server can start or it causes an infinite load time. I have searched through what code I could see available through here but cannot find an issue with cataclysm standalone, therefore I believe it is something to do with interaction between other mods. The mods being run at the time are:

Cataclysm
Recipe Browser
Smart Doors (from 1.4)
Lan's Shared Map
Max Stack Plus Extra
VeinMiner
Wing Slot
Calamity Mod Music
Calamity Mod (No Calamity Music)
Calamity's Vanities

I have not done very extensive research into this but I thought it would be helpful for you to know, Have a great rest of your day.

**Comment by steviegt6** [comment]
Known issue, thanks for putting it on the issue tracker, though.
It's an issue with how I handle glowmasks, as well as a forgotten check for server-side loading.

**Comment by steviegt6** [comment]
Fixed in eb8a365c8f918cae5e5d6d219157040730a6c66c
